### ISSUE TITLE
i18n not working

### ISSUE THREAD

**Issue by sebilasse** [dojo/framework#807] opened 2020-06-16 03:47 UTC
**Bug** 

Package Version: 7, current stable and next

**Code**

dojo i18n is not working at all here

Hello,
made the [page for ActivityPub Conference](https://conf.activitypub.rocks) _2020_ again with dojo and finally want to add nls –
but since dojo 7 the i18n part is not working anymore for me.
For https://redaktor.me/ I used 6 where it was fine, however :

If I build without any "locales" in .dojorc then everything is fine.

If I build with "locales" then it raises many errors about `cldr-data` [although we don't use it yet].

If I install `cldr-data` then the acorn error below prevents any building …

**Expected behavior:**

building fine

**Actual behavior:**

a non-self-explanatory Syntax error thrown by "acorn" -
`
Unexpected token (7:4)
Parser.pp$4.raise
`
the same as described here by multiple users here 
https://github.com/nuxt-community/nuxt-i18n/issues/78

**Comment by sebilasse** [comment] 2020-06-16 05:03
Hm,

this disappeared. Closing it.

For reference
While I don't know what the reason was, it might have been one of the following 

- renamed .nls.ts to .nls.tsx
- renamed foo.de.nls ... to ./de/foo.nls ...
- restarted the machine

**Comment by agubler** [comment] 2020-06-18 11:40
Hey @sebilasse, the reason that there are build time errors when using setting locales for i18n it that the new plugin requires the `cldr-data` dependency. I thought that was called out in the dojo.io i18n reference guide but I cannot seem to find it.

As for the acorn error, nothing related to i18n uses acorn, so I'm not sure that related to that.

Could you provide a cutdown repro that we could look into?

**Comment by agubler** [comment] 2020-07-10 07:19
@sebilasse Did you have any luck reproducing this issue?

**Comment by agubler** [comment] 2020-07-28 09:32
@sebilasse Is this still an issue for you?

**Comment by agubler** [comment] 2021-03-16 17:50
@sebilasse closing this issue as it's been sometime since we've heard from you 😄 Feel free to re-open if the issue resurfaces.

**Closed by agubler** 2021-03-16 17:50 UTC
Labels: area: i18n, question
