### ISSUE TITLE
Set title on route change

### ISSUE THREAD

**Issue by agubler** [dojo/framework#614] opened 2019-12-21 11:45 UTC
**Enhancement**

Add an enhancement to the router that can set the document title on a route change. This should be able to the declaratively defined in the routing configuration for static titles. If there are dynamic requirements a callback should be able to be registered on router initialisation. The callback will receive all the route details (params, query params, declarative title, outlet id, path . etc) and return the `title` to set.

**Comment by matt-gadd** [comment] 2020-02-13 13:49
closed as a dupe of https://github.com/dojo/framework/issues/601

**Closed by matt-gadd** 2020-02-13 13:49 UTC
Labels: area: routing, enhancement
