### ISSUE TITLE
Change `extraClasses` to accept `(string | null)[]` such that `this.theme` can be used

### ISSUE THREAD

**Issue by tomdye** [dojo/framework#161] opened 2018-11-09 13:26 UTC
To support the [widgets material epic](https://github.com/dojo/widgets/issues/615) we should improve `extraClasses` to support the output of `this.theme`. This will allow themed classes to be passed to widgets.

This should not be a breaking change.

## Current use

```ts
w(MyWidget, {
   extraClasses: { root: css.myClass }
})
```

## future uses

```ts
w(MyWidget, {
   extraClasses: { root: [css.myClass, css.mySecondClass] }
})

w(MyWidget, {
   extraClasses: { root: this.theme(css.myClass) }
})

w(MyWidget, {
   extraClasses: { root: this.theme([css.myClass, css.mySecondClass]) }
})

```

**Comment by agubler** [comment] 2018-11-11 12:32
Duplicate of #134

**Closed by agubler** 2018-11-11 12:32 UTC
